#!/bin/sh -l
# FILENAME:  power.sbatch

#SBATCH --account=bphm
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --partition=cpu
#SBATCH --cpus-per-task=24
#SBATCH --qos=normal
#SBATCH --time=48:00:00
#SBATCH --job-name power
#SBATCH --array=1-16
#SBATCH --output=power_%A_%a.out

module load r/4.2.2

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export VECLIB_MAXIMUM_THREADS=1

Rscript power_grid.R